target:

U_SAMPLE_HOME=../../..

include $(U_SAMPLE_HOME)/config.mk
include ../common.mk

U_TARGET=cppRates
U_INCLUDES+=-I..

#U_CFLAGS+=-DSPI_UTIL_CLOCK_EVENTS

include $(U_SPI_HOME)/makefiles/build/lib.mk

