target:

U_SAMPLE_HOME=../../..
include $(U_SAMPLE_HOME)/config.mk

U_SRC_DIR=.
U_INC_DIR=.
U_TARGET=clib-replay
U_SERVICE_DLL=clib
U_VCPROJ_OPTIONS+=--exe=..\G_ABI\$(U_TARGET).exe

include $(U_SPI_HOME)/makefiles/spi/replay.mk

