all: code code-excel code-dotnet code-python

U_SAMPLE_HOME=../../..
include $(U_SAMPLE_HOME)/config.mk

U_SERVICE=cpplib
#U_TDIRNAME=../types
U_CONFIG_DIR=.
U_PYTHON_DIR=../python
U_EXCEL_DIR=../excel
U_DOTNET_DIR=../dotnet
U_COMPANY_NAMESPACE=sartorial
U_COMPANY_NAME=Sartorial Programming Ltd.

include $(U_SPI_HOME)/makefiles/spi/spcl.mk
include $(U_SPI_HOME)/makefiles/spi/spcli.mk
include $(U_SPI_HOME)/makefiles/spi/sppy.mk
include $(U_SPI_HOME)/makefiles/spi/spxl.mk

