cli:

U_SAMPLE_HOME=../../..
U_CLR=1
include $(U_SAMPLE_HOME)/config.mk

U_INCLUDES=-I$(G_QL_BOOST_HOME)
U_NAMESPACE=sartorial
U_COMPANY_NAME=Sartorial Programming Ltd.

include $(U_SPI_HOME)/makefiles/spi/cli.mk

