pyd:

U_SAMPLE_HOME=../../..
include $(U_SAMPLE_HOME)/config.mk

U_INCLUDES=$(G_BOOST_INCLUDES)

U_INSTALL_FILES=$(G_SPI_DLLS)\
$(G_INSTALL_DLL_PFX)clib$(G_INSTALL_DLL_EXT)\
$(G_INSTALL_PYD_PFX)py_clib$(G_INSTALL_PYD_EXT)

include $(U_SPI_HOME)/makefiles/spi/pyd.mk

