pyd:

U_SAMPLE_HOME=../../..
include $(U_SAMPLE_HOME)/config.mk

U_INCLUDES=-I$(G_QL_BOOST_HOME)

U_INSTALL_FILES=$(G_SPI_DLLS)\
$(G_INSTALL_DLL_PFX)ql$(G_INSTALL_DLL_EXT)\
$(G_INSTALL_PYD_PFX)py_ql$(G_INSTALL_PYD_EXT)

include $(U_SPI_HOME)/makefiles/spi/pyd.mk

